<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="cylinder_link_robot">

  <!-- Macro for a Cylindrical Link -->
  <xacro:macro name="cylinder_link" params="parent_link child_link prefix cylinder_radius cylinder_length">
    <link name="${prefix}_cylinder_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${cylinder_radius}" length="${cylinder_length}"/>
        </geometry>
        <material name="yellow">
          <color rgba="1 1 0 1"/>
        </material>
      </visual>

      <!-- Collision element -->
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${cylinder_radius}" length="${cylinder_length}"/>
        </geometry>
      </collision>
    </link>

    <joint name="${prefix}_cylinder_joint" type="fixed">
      <parent link="${parent_link}"/>
      <child link="${prefix}_cylinder_link"/>
      <origin xyz="0 0 ${cylinder_length / 2}" rpy="0 0 0"/>
    </joint>

    <joint name="${prefix}_to_child_joint" type="fixed">
      <parent link="${prefix}_cylinder_link"/>
      <child link="${child_link}"/>
      <origin xyz="0 0 ${cylinder_length / 2}" rpy="0 0 0"/>
    </joint>
  </xacro:macro>

</robot>
