# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    Group1_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

Group1_controller:
  ros__parameters:
    joints:
      - floating_1
      - floating_2
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity