# Default initial positions for isaac_twin's ros2_control fake system

initial_positions:
  spherical_1_x: 0
  spherical_1_y: 0
  spherical_1_z: 2
  spherical_2_x: 0
  spherical_2_y: 1
  spherical_2_z: 0
  spherical_3_x: 0
  spherical_3_y: 1
  spherical_3_z: 0
  spherical_4_x: 0
  spherical_4_y: 1
  spherical_4_z: 0