# Default initial positions for isaac_twin's ros2_control fake system

initial_positions:
  prismatic_joint_1: 2
  prismatic_joint_2: 1
  prismatic_joint_3: 1
  prismatic_joint_4: 1
  spherical_1_x: 0
  spherical_1_y: 0
  spherical_1_z: 0
  spherical_2_x: 0
  spherical_2_y: 1.5707
  spherical_2_z: 0
  spherical_3_x: 0
  spherical_3_y: 0
  spherical_3_z: 0
  spherical_4_x: 0
  spherical_4_y: 0
  spherical_4_z: 0