planning_plugins:
  - chomp_interface/CHOMPPlanner
# The order of the elements in the adapter corresponds to the order they are processed by the motion planning pipeline.

planning_time_limit: 2.0
max_iterations: 1000
max_iterations_after_collision_free: 5
smoothness_cost_weight: 0.01
obstacle_cost_weight: 1.0
learning_rate: 0.004
animate_path: true
add_randomness: false
smoothness_cost_velocity: 0.0
smoothness_cost_acceleration: 1.0
smoothness_cost_jerk: 0.0
hmc_discretization: 0.01
hmc_stochasticity: 0.01
hmc_annealing_factor: 0.99
use_hamiltonian_monte_carlo: false
ridge_factor: 0.001
use_pseudo_inverse: false
pseudo_inverse_ridge_factor: 1e-4
animate_endeffector: false
animate_endeffector_segment: "Drone4"
joint_update_limit: 0.2
collision_clearance: 0.1
collision_threshold: 1.0
random_jump_amount: 0.07
use_stochastic_descent: true
enable_failure_recovery: true
max_recovery_attempts: 10
# trajectory_initialization_method: "quintic-spline"
trajectory_initialization_method: "fillTrajectory"

# request_adapters:
#   default_planner_request_adapters/AddTimeOptimalParameterization
#   default_planner_request_adapters/ResolveConstraintFrames
#   default_planner_request_adapters/FixWorkspaceBounds
#   default_planner_request_adapters/FixStartStateBounds
#   default_planner_request_adapters/FixStartStateCollision
#   default_planner_request_adapters/FixStartStatePathConstraints
# response_adapters:
#   default_planning_response_adapters/AddTimeOptimalParameterization
#   default_planning_response_adapters/ValidateSolution
#   default_planning_response_adapters/DisplayMotionPath