<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="chain">

  <!-- Define parameters -->
  <xacro:property name="cylinder_radius" value="0.01"/>
  <xacro:property name="cylinder_length" value="0.1"/>
  <xacro:property name="num_links" value="20"/>

  <!-- Macro for Chain Links -->
  <xacro:macro name="chain" params="parent_link child_link prefix">
    <!-- Define the chain starting from the parent link -->
    <xacro:macro name="chain_link" params="index parent_link remaining_links">
      <link name="${prefix}_link_${index}">
        <visual>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
            <cylinder radius="${cylinder_radius}" length="${cylinder_length}"/>
          </geometry>
          <material name="green">
            <color rgba="0 1 0 1"/>
          </material>
        </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
           <cylinder radius="${cylinder_radius}" length="${cylinder_length}"/> 
        </geometry>
      </collision>        
      </link>

      <joint name="${prefix}_joint_${index}" type="continuous">
        <parent link="${parent_link}"/>
        <child link="${prefix}_link_${index}"/>
        <origin xyz="0 0 ${cylinder_length / 2}" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
      </joint>

      <!-- Recursively create the next link if there are remaining links -->
      <xacro:if value="${remaining_links > 0}">
        <xacro:chain_link index="${index + 1}" parent_link="${prefix}_link_${index}" remaining_links="${remaining_links - 1}"/>
      </xacro:if>
    </xacro:macro>

    <!-- Start the chain from the parent link -->
    <xacro:chain_link index="1" parent_link="${parent_link}" remaining_links="${num_links - 2}"/>

    <!-- Define the final joint to the child link -->
    <joint name="${prefix}_joint_${num_links}" type="continuous">
      <parent link="${prefix}_link_${num_links - 1}"/>
      <child link="${child_link}"/>
      <origin xyz="0 0 ${cylinder_length / 2}" rpy="0 0 0"/>
      <axis xyz="0 0 1"/>
    </joint>
  </xacro:macro>

</robot>
